[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python FastAPI app - no build step needed'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"